apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Base directory of the kustomize instance
  - ../../../../../kustomize/instances/aap

patches:
  - path: secrets/secret-aap-admin-password.yaml