apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Base directory of the kustomize instance
  - ../../../../../kustomize/instances/rhdh

patches:
  - path: secrets/secret-ansible-platform.yaml
  - path: secrets/secret-api-token.yaml
  - path: secrets/secret-github-app-integration.yaml
  - path: secrets/secret-backend.yaml 
  - path: secrets/rhdh-client-secret.yaml