apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rhsso

resources:
# Injecting the secrets from the .secrets directory into the base directory
# Demo purpose only, real use External Secrets Operator or Vault
  - ../../.secrets/instances/rhsso-config

patches:
# RHSSO client secret - direct integration with RHSSO for Developer Hub SSO
#  - path: patches/keycloakclient.yaml
  - path: patches/keycloakclient-aap.yaml